version: '3'

services:

  propostas-mysql:
    image: 'mysql:5.7'
    container_name: propostas-mysql
    expose:
      - 3306
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=proposta
      - MYSQL_ROOT_HOST=%

  propostas-api:
    depends_on:
      - propostas-mysql
    container_name: propostas-api
    image: proposta-jar
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod



      

